### ISSUE TITLE
网工修炼之道（slides）

### ISSUE THREAD

**Issue by ProfessorX** [wzpan/wzpan.github.io#25]
http://onmw7y6f4.bkt.clouddn.com/clumsy%2520cser.pdf

Error: No such domain.

Please update the link or remove it. Many thanks~

**Comment by wzpan** [comment]
@ProfessorX Thank you for reminding. I will update the link later. For now you can get access to the slides at [here](https://pan.baidu.com/s/1mkIQwPvdJNCv2kjBFF2jqg).
